# Generated by Django 4.2.4 on 2023-09-21 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aaaa.user')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('duration', models.BigIntegerField()),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aaaa.product')),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aaaa.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aaaa.user')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timecode', models.BigIntegerField()),
                ('isWathed', models.BooleanField(default=False)),
                ('timestamp', models.BigIntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aaaa.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aaaa.user')),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
