# Generated by Django 4.2.4 on 2023-09-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aaaa', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='access',
            unique_together={('user', 'product')},
        ),
    ]
